name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Publish
        run: npm run deploy
